name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/recipe-backend:latest ./backend

      - name: Push Backend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/recipe-backend:latest

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/recipe-frontend:latest ./frontend

      - name: Push Frontend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/recipe-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd recipe-book-docker-cicd

            docker compose pull

            docker compose down

            docker compose up -d